function isArray(obj){if(obj.constructor.toString().indexOf("Array")==-1)
return false;else
return true;}
function trackOutboundLink(link,category,action,newWindow){try{ga('send','event',category,link.hostname,link.href.replace(/.*?:\/\//g,""));}catch(err){}}
String.prototype.endsWith=function(pattern){var d=this.length-pattern.length;return d>=0&&this.lastIndexOf(pattern)===d;};$.fn.reverse=[].reverse;var delay=(function(){var timer=0;return function(callback,ms){clearTimeout(timer);timer=setTimeout(callback,ms);};})();function chroniqueToolTip(){$('#left-col .reviewLink').tooltip({predelay:0,position:"center right",delay:100,direction:'right',effect:'slide',relative:true});$('#right-col .reviewLink').tooltip({predelay:0,position:"center left",delay:100,direction:'right',effect:'slide',relative:true});}
function format(band){return band.name+" &lt;"+band.id+"&gt";}
jQuery.fn.extend({findPos:function(){var obj=jQuery(this).get(0);var curleft=obj.offsetLeft||0;var curtop=obj.offsetTop||0;while(obj=obj.offsetParent){curleft+=obj.offsetLeft
curtop+=obj.offsetTop}
return{x:curleft,y:curtop};}});function lookup(event){var inputString=$('#searchAutoComplete').val();if(inputString.length<3){$('#suggestions').slideUp("slow");}else{if(event.keyCode==27){$('.searchResultLink.selected').removeClass('selected');$('#suggestions').slideUp("slow");}else if(event.keyCode==40||event.keyCode==38||event.keyCode==13){var nbSelected=$('.searchResultLink.selected').length;if(event.keyCode==13&&nbSelected>0){window.location.href=$('.searchResultLink.selected').attr('href');return false;}else if(event.keyCode==40&&nbSelected==0){$('#suggestions').fadeIn();$($('.searchResultLink')[0]).addClass('selected');}else if(nbSelected!=0){$('#suggestions').slideDown("slow");var collection=$('.searchResultLink');if(event.keyCode==38){collection=collection.reverse();}
var applyOnNext=false;collection.each(function(){if(applyOnNext){$(this).addClass('selected');applyOnNext=false;}else if($(this).hasClass('selected')){applyOnNext=true;$(this).removeClass('selected');}});if(applyOnNext){$(collection[0]).addClass('selected');}}}else{$.post("/_ajax/search.php",{queryString:""+inputString+""},function(data){$('#suggestions').html(data);$('#suggestions').slideDown("slow");});}}}
function showHideComments(chroId,albumId,urlPt){if($('#chronique-comments-'+chroId).is(':hidden')){$('#chronique-text-'+chroId).css({opacity:1}).fadeTo("normal",0,function(){if($('#chronique-comments-'+chroId).html().length==0){$.ajax({type:"GET",url:"/_ajax/getLastComments.php",data:"albumId="+albumId+"&urlPt="+urlPt,success:function(msg){$('#chronique-comments-'+chroId).html(msg);switchToComment(chroId);}});}else{switchToComment(chroId);}});}else{$('#chronique-comments-'+chroId).css({opacity:1}).fadeTo("normal",0,function(){$('#chronique-text-'+chroId).css({'display':'block'});$('#chronique-text-'+chroId).css({opacity:0}).fadeTo("normal",1);$('#chronique-comments-'+chroId).css({'display':'none'});});}}
function switchToComment(chroId){$('#chronique-comments-'+chroId).css({'display':'block'});$('#chronique-comments-'+chroId).css({opacity:0}).fadeTo("normal",1);$('#chronique-text-'+chroId).css({'display':'none'});}
function resize(obj){var id=$(obj).attr('id');alert(id);var borderVt=150;var borderHz=40;var origSizeW=$(id).width();var origSizeH=$(id).height();var ratioVt=(origSizeW/origSizeH);var ratioHz=(origSizeH/origSizeW);var winW=$(window).width();var winH=$(window).height();var screenSizeW=Math.round(winW-borderHz);var screenSizeH=Math.round(winH-borderVt);alert('Origin : '+origSizeW+' '+screenSizeW+' '+screenSizeH);if(origSizeW>=origSizeH){var newHeight=Math.round(screenSizeW*ratioHz);if(newHeight<=screenSizeH){$(id).css("width",screenSizeW);$(id).css("height",newHeight);}
else{$(id).css("height",screenSizeH);}}
else{$(id).css("height",screenSizeH);}};function initComment(){myBbcodeSettings={nameSpace:"bbcode",previewParserPath:"~/sets/bbcode/preview.php",markupSet:[{name:'Gras',key:'B',openWith:'[b]',closeWith:'[/b]'},{name:'Italique',key:'I',openWith:'[i]',closeWith:'[/i]'},{name:'Souligné',key:'U',openWith:'[u]',closeWith:'[/u]'},{separator:'---------------'},{name:'Liste à puces',openWith:'[list]\n',closeWith:'\n[/list]'},{name:'Liste numérotée',openWith:'[list=[![Starting number]!]]\n',closeWith:'\n[/list]'},{name:'Element de liste',openWith:'[*] '},{separator:'---------------'},{name:'Citation',openWith:'[quote]',closeWith:'[/quote]'},{separator:'---------------'},{name:'Nettoyer',className:"clean",replaceWith:function(h){return h.selection.replace(/\[(.*?)\]/g,"")}},]}
$('.bbcode').markItUp(myBbcodeSettings);$('#commentaire_form').submit(function(){var note=$('#commentaire\\[note\\]').val();var comment=$('#commentaire\\[texte\\]').val();if(note.length==0){$('#commentaire_message').html('Vous devez choisir une note.').show();}else if((note<1||note>19)&&comment.length==0){$('#commentaire_message').html('Pour une note en dessous de 1 ou au dessus de 19 le commentaire est obligatoire.').show();}else{$.ajax({type:'POST',dataType:'json',url:$('#commentaire_form').attr('action'),data:{'commentaire[texte]':comment,'commentaire[note]':note,'ajax':true},success:function(data,textStatus,XMLHttpRequest){if(data.saved){$('#commentaire_form').hide('slow',function(){if(data.content.length>0){if(data.update!=false&&$('#comment-'+data.update).length>0){$('#comment-'+data.update).replaceWith(data.content);}else{$('#commentaires').prepend(data.content);}}
var s='';if(data.nb>1){s='s';}
$('#moy_lecteurs').html(data.moy_lecteur);$('#userCommentHeader').html(data.msg);});}else{var errors='';for(var idx=0;idx<data.errors.length;idx++){errors+=data.errors[idx]+'<br>'}
$('#commentaire_message').html(errors);$('#commentaire_message').show();}},error:function(xhr,textStatus,errorThrown){}});}
return false;});var initial=10;if($('#note_txt').html()!='__'){initial=parseInt($('#note_txt').html());}
if($("#note").length>0){$("#note").slider({step:0.5,min:0,max:20,value:initial,slide:function(event,ui){$('#note_txt').html(ui.value);$('#commentaire\\[note\\]').val(ui.value);if(ui.value<1||ui.value>19){$('#commentaire_warning').show();}else{$('#commentaire_warning').hide();}}});}}
function addAddToListAction(){$('.addToList').each(function(){var link=this;$(this).bind("click",function(){$.ajax({type:'GET',dataType:'json',url:this.href,success:function(data,textStatus,XMLHttpRequest){if(data.message){$(link).replaceWith("<span>"+data.message+"</span>");$(link).fadeOut(800).fadeIn(800).fadeOut(400).fadeIn(400);}else{var errors='';for(var idx=0;idx<data.errors.length;idx++){errors+=data.errors[idx]+' ';}
$(" <span class='error'>"+errors+"</span>").insertAfter(link);}},error:function(xhr,textStatus,errorThrown){}});return false;});});}
function deleteFromList(){$('.deleteFromList').each(function(){var link=this;$(this).bind("click",function(){$.ajax({type:'GET',dataType:'json',url:link.href,success:function(data,textStatus,XMLHttpRequest){if(data.message){$(link).html(data.message);}else{var errors='';for(var idx=0;idx<data.errors.length;idx++){errors+=data.errors[idx]+' ';}
alert(errors);}},error:function(xhr,textStatus,errorThrown){}});return false;});});}
function removeFromListAction(){$('.removeFromList').each(function(){var link=this;$(this).bind("click",function(){if(confirm('Voulez vous supprimer cet élément?')){$.ajax({type:'GET',dataType:'json',url:link.href,success:function(data,textStatus,XMLHttpRequest){if(data.message){$(link).parent().parent().css('opacity',0.3);$(link).parent().remove();}else{var errors='';for(var idx=0;idx<data.errors.length;idx++){errors+=data.errors[idx]+' ';}
alert(errors);}},error:function(xhr,textStatus,errorThrown){}});return false;}});});}
function tag_combiner(tagName){tags.push(tagName);tags.sort();param='';for(i=0;i<=tags.length-1;i++){param=param+encodeURIComponent(tags[i])+'+';}
window.location.replace(url+param.slice(0,-1));}
function getGroupeSlugFromUrl(url){var slug='';var pos=url.indexOf('/groupe/')+8;if(pos>0){var slug=url.substr(pos,url.length-pos);}
return slug;}
$(document).ready(function(){jQuery(function(){jQuery('a:not([href*="'+document.domain+'"])').click(function(e){if(this.href.length>0&&this.href.indexOf('metalorgie.com')==-1){var newWindows=false;if(e.which==2||e.metaKey||e.ctrlKey){newWindows=true;}
trackOutboundLink(this,'Outbound Links',this.href,newWindows);if(!newWindows){e.preventDefault();setTimeout('document.location = "'+this.href+'"',100);}}});});chroniqueToolTip();$('#colorSwitcher').bind('click',function(){var body=$('body');var CssClass='body-metal';if(body.hasClass('body-metal')){body.addClass('body-punk').removeClass('body-metal');$(this).html('Color Me Blood Red');CssClass='body-punk';}else{body.addClass('body-metal').removeClass('body-punk');$(this).html('Pink turns to blue');}
$.ajax({url:$(this).attr('href')+"?CssClass="+CssClass});return false;});addAddToListAction();deleteFromList();$("#searchAutoComplete").keyup(function(event){if(event.keyCode=='38'||event.keyCode=='40'){lookup(event)}else{delay(function(){lookup(event)},300);}});$("#searchAutoComplete").blur(function(){$('#suggestions').fadeOut();});$('#searchForm').bind('submit',function(){if($('.searchResultLink.selected').length>0){return false}});$(".share").tooltip({effect:'slide',position:"center right",relative:true,delay:30});if($('.bbcode').length>0){initComment();}
$.tools.dateinput.localize("fr",{months:'Janvier,F&eacute;vrier,Mars,Avril,Mai,Juin,Juillet,Ao&ucirc;t,'+
'Septembre,Octobre,Novembre,D&eacute;cembre',shortMonths:'jan,f&eacute;v,mar,avr,mai,jun,jul,ao&ucirc;,sep,oct,nov,d&eacute;c',days:'Dimanche,Lundi,Mardi,Mercredi,Jeudi,Vendredi,Samedi',shortDays:'dim,lun,mar,mer,jeu,ven,sam'});$(":date").dateinput({lang:'fr',format:'dd/mm/yyyy',offset:[30,0]});$("ul.tab-nav").tabs("div.panes > div",{current:'on'});$(".tabify ul.content-table").tabs("div.panes > div",{current:'active'});$("a.groupe").each(function(){$('<span style="display:none;" class="tip-box tip-band"></span>').insertAfter($(this));});$("a.groupe").tooltip({predelay:1000,position:"bottom right",delay:100,relative:true,effect:'slide',onBeforeShow:function(){if(this.getTip().html().length==0){theUrl=this.getTrigger().attr("href");getAjaxData(theUrl,this.getTip());}}});function getAjaxData(theUrl,$tip){$tip.text('Chargement...');var slug=getGroupeSlugFromUrl(theUrl);$.ajax({url:'/_ajax/getTipForBand.php?band='+slug,success:function(response){$tip.html(response);}});}
$('#switcher').mouseover(function(){if($(this).css('background-image').indexOf('switcher.png')!=-1){var reg=new RegExp("(switcher.png)","g");$(this).css('background-image',$(this).css('background-image').replace(reg,'switcher-hover.png'));}else if($(this).css('background-image').indexOf('switcher_punk.png')!=-1){var reg=new RegExp("(switcher_punk.png)","g");$(this).css('background-image',$(this).css('background-image').replace(reg,'switcher-hover_punk.png'));}});$('#switcher').mouseout(function(){if($(this).css('background-image').indexOf('switcher-hover.png')!=-1){var reg=new RegExp("(switcher-hover.png)","g");$(this).css('background-image',$(this).css('background-image').replace(reg,'switcher.png'));}else if($(this).css('background-image').indexOf('switcher-hover_punk.png')!=-1){var reg=new RegExp("(switcher-hover_punk.png)","g");$(this).css('background-image',$(this).css('background-image').replace(reg,'switcher_punk.png'));}});$("#slider").scrollable({circular:true}).autoscroll({autoplay:true,interval:5000,autopause:true}).navigator({activeClass:'on',navi:'#dossier_switcher'});if($(window).width()>1250){$(window).scroll(function(){var scrollPosition=$(window).height()+$(window).scrollTop();var documentHeight=$(document).height();if(documentHeight-scrollPosition<400){var top=246-350+(documentHeight-scrollPosition);$('#filigrane-right').css('top',top+'px');$('#filigrane-left').css('top',top+'px');}else{$('#filigrane-right').css('top','');$('#filigrane-left').css('top','');}});var width=$(window).width();w=((width-1250)/2)-121;$('#filigrane-left').css('left',w+'px');w=((width-1250)/2)-340;$('#filigrane-right').css('right',w+'px');}
$('.imageContainer').bind('mouseover',function(){$(this).find('.toolImg').show();});$('.imageContainer').bind('mouseout',function(){$(this).find('.toolImg').hide();});$('a.confirm').bind('click',function(){if(!confirm('Vous êtes sûr?')){return false;}});$('.news.short').bind('mouseenter',function(){$(this).find('.share').show();});$('.news.short').bind('mouseleave',function(){$(this).find('.share').hide();});$('#flattrBox').bind('mouseenter mouseleave',function(){$('#flattrBox .info').toggle();});removeFromListAction();if($('#photo_gallerie').length>0){$.nyroModalSettings({addImageDivTitle:true,galleryCounts:function(nb,total,elts,settings){if(total>1)
settings.title+=(settings.title?' - ':'')+nb+'/'+total+' - '+$('#photo_txt_'+$(settings.from).attr('id')).val();},endShowContent:function(elts,settings){$.get('/_ajax/incrementerVuesPhoto.php?photo='+$(settings.from).attr('id'));ga('send','pageview',settings.url);}});}
if($('#score_chart').length>0){chart=new Highcharts.Chart({chart:{renderTo:'score_chart',defaultSeriesType:'bar',margin:[40,20,75,10]},credits:{enabled:false},colors:['#89A54E','#E4EB76','#DB843D','#AA4643'],title:{text:'Répartition des notes',align:'left',floating:true,x:6,y:35,style:{color:'#666',fontSize:'12px'}},xAxis:{title:{text:null},labels:{enabled:false}},yAxis:{min:0,title:{text:null}},legend:{backgroundColor:'#FFFFFF',reversed:true},tooltip:{formatter:function(){return ''+
this.series.name+': '+this.y+'';}},plotOptions:{series:{stacking:'normal'}},series:scoreData});}
if($('#views_chart').length>0){Highcharts.setOptions({lang:{months:['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],weekdays:['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi']}});var chart=new Highcharts.Chart({chart:{renderTo:'views_chart',zoomType:'x',spacingRight:20},credits:{enabled:false},title:{text:'Vues de la page de '+groupe_nom},xAxis:{type:'datetime',maxZoom:14*24*3600000,title:{text:null}},yAxis:{title:{text:'Nomre de vues'},min:0,startOnTick:false,showFirstLabel:false},tooltip:{shared:true},legend:{enabled:false},tooltip:{formatter:function(){return Highcharts.numberFormat(this.y,0)+' vues</b> le '+Highcharts.dateFormat('%A %e %B %Y',this.x);}},plotOptions:{area:{fillColor:{linearGradient:[0,0,0,300],stops:[[0,'rgba(0, 0, 0, 0.5)'],[1,'rgba(2,0,0,0)']]},lineWidth:1,marker:{enabled:false,states:{hover:{enabled:true,radius:5}}},shadow:false,states:{hover:{lineWidth:1}}}},series:[{type:'area',name:'Vues par jour',pointInterval:24*3600*1000,pointStart:Date.UTC(year_start,month_start,day_start),data:data}]});}
$(function(){if($('#mainPicture').length>0){var $sidebar=$("#photo-details"),$window=$(window),offset=$sidebar.offset(),topPadding=15;function movePhotoDetails(){if($window.scrollTop()>offset.top){$sidebar.stop().animate({marginTop:$window.scrollTop()-offset.top+topPadding});}else{$sidebar.stop().animate({marginTop:0});}}
$window.scroll(function(){movePhotoDetails();});function set_body_height(){var wh=$(window).height();var maxHeight=$('#mainPicture').attr('data-maxheight');if(wh>maxHeight){wh=maxHeight;}
$('#mainPicture').height(wh);}
$(window).bind('resize',function(){set_body_height();});movePhotoDetails();set_body_height();}
$(document).keydown(function(e){if(e.keyCode==39||e.keyCode==75){if($('#mainPicture .next').length>0){window.location=$('#mainPicture .next').attr('href');}}else if(e.keyCode==37||e.keyCode==74){if($('#mainPicture .prev').length>0){window.location=$('#mainPicture .prev').attr('href');}}});$('#fullScreen').bind('click',function(e){screenfull.request();});});});